# To build: docker build -t bwa:v0.1 - < Dockerfile.mapping_bwa

FROM debian:buster

ENV pengu_software_version_htslib=1.10.2 \
pengu_software_version_samtools=1.10 \
pengu_software_version_bwa=0.7.17

RUN apt-get update && apt-get install -y bzip2 curl g++ make zlib1g-dev libbz2-dev liblzma-dev unzip \
autoconf libncurses5-dev 

# Install htslib
RUN curl -fsSL "https://github.com/samtools/htslib/releases/download/${pengu_software_version_htslib}/htslib-${pengu_software_version_htslib}.tar.bz2" | tar -xj
WORKDIR htslib-${pengu_software_version_htslib}
RUN ./configure && make && make install
ENV PATH "$PATH:/htslib-${pengu_software_version_htslib}"
RUN ln -s /usr/local/lib/libhts.so.3 /usr/lib/

# Install samtools
WORKDIR /
RUN curl -fsSL "https://github.com/samtools/samtools/releases/download/${pengu_software_version_samtools}/samtools-${pengu_software_version_samtools}.tar.bz2" | tar -xj
WORKDIR samtools-${pengu_software_version_samtools}
RUN ./configure && make && make install
ENV PATH "$PATH:/samtools-${pengu_software_version_samtools}"

# Install BWA
WORKDIR /
RUN curl -fsSL "https://github.com/lh3/bwa/releases/download/v${pengu_software_version_bwa}/bwa-${pengu_software_version_bwa}.tar.bz2" | tar -xj
RUN cd bwa-${pengu_software_version_bwa} && make
ENV PATH "$PATH:/bwa-${pengu_software_version_bwa}"