FROM debian:buster

ENV pengu_software_version_FastQC=0.11.7 \
pengu_software_version_TrimGalore=0.6.5

ENV PACKAGES="wget openjdk-11-jre-headless python3.7 python3-cutadapt cutadapt unzip libfindbin-libs-perl"

RUN apt-get update \
&& apt-get install -y $PACKAGES

RUN wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v${pengu_software_version_FastQC}.zip \
&& unzip fastqc_v${pengu_software_version_FastQC}.zip \
&& chmod +x FastQC/fastqc \
&& mv FastQC /usr/local/bin \
&& rm -r fastqc*

ENV PATH ${PATH}:/usr/local/bin/FastQC/

RUN wget -O trim_galore.tar.gz https://github.com/FelixKrueger/TrimGalore/archive/${pengu_software_version_TrimGalore}.tar.gz \
&& tar -xzf trim_galore.tar.gz \
&& mv TrimGalore-${pengu_software_version_TrimGalore}/trim_galore /usr/local/bin \
&& rm -r trim_galore*

RUN env | grep "pengu_software_version" | sed 's/pengu_software_version_//g' > /etc/pengu_software_version.txt

RUN if [ -d "/.singularity.d/env" ] ; \
then grep "pengu_software_version" /.singularity.d/env/* | awk '{print $2}' | sed 's/pengu_software_version_//g' > /etc/pengu_software_version.txt ; \
fi

RUN apt-get install -y python3-pip && pip3 freeze >> /etc/pengu_software_version.txt
